### ISSUE TITLE
great!

### ISSUE THREAD

**Issue by yuedajiong** [VITA-Group/4DGen#1]

**Comment by Ir1d** [comment]
Thanks!

**Comment by yuedajiong** [comment]
Hi, great-master: @Ir1d 

Just as I know, there are at least 7+ 4d/dynamic/spacetime/spat-temp/...  papers from Sep to Dec.
What are the differents, what is the best/better?
What is the ideal 4D representation? and then what is the best dyn-reconstrcution algothim?

Not any challange.   
I used to focued on the surface-recon,  now I am focusing on dynamic.  So I have this stupid confusion.

Thanks.
