### ISSUE TITLE
The training time is long.

### ISSUE THREAD

**Issue by Fly-Pluche** [VITA-Group/4DGen#3]
Hi,
Train on a single A100 GPU，point=25000, needs about 4h, longer than mentioned in the paper.
![image](https://github.com/VITA-Group/4DGen/assets/73021377/7694abb1-86d9-41c7-9679-7e177dbed543)

![image](https://github.com/VITA-Group/4DGen/assets/73021377/9fcb0a85-98f4-4319-9852-a306cb6670c7)

![image](https://github.com/VITA-Group/4DGen/assets/73021377/133ec870-66a6-455f-ac1d-a3cd6ffd62f3)

**Comment by YuyangYin** [comment]
hi. Have you changed default config? We have tested code on 3090 and V100. The time is about 2h. By the way, as shown in your picture the time estimated in first hundreds iteration is not accuracy. You can wait for a moment and see how much time it estimates.
